plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  Max: 12
  MaxOptionalParameters: 12

Layout/LineLength:
  Max: 140

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

Metrics/ClassLength:
  Max: 130

RSpec/SpecFilePathFormat:
  IgnoreMethods: true
  CustomTransform:
    OAuth: oauth
